apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ktailor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ktailor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ktailor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ktailor.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "ktailor.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: certs
              mountPath: /etc/ktailor/certs
              readOnly: true
            - name: config
              mountPath: /etc/ktailor/ktailor.yaml
              subPath: ktailor.yaml
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: certs
          secret:
            # Name of the secrets which gets generated from cert-manager
            secretName: {{ .Values.certs.secretName | default (printf "%s-certs" (include "ktailor.fullname" .)) }}
        - name: config
          configMap:
            name: {{ include "ktailor.fullname" . }}

