---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetravel-test
  namespace: ktailor
  labels:
    # This label triggers the Webhook
    ktailor.io/fit: "local.lft-plus222d" # inserts libfaketime and moves pod 222d into future

spec:
  replicas: 1
  selector:
    matchLabels:
      app: libfaketime-test
  template:
    metadata:
      labels:
        app: libfaketime-test
    spec:
      containers:
      - name: libfaketime-test
        image: debian:stable
        command: ["/bin/sh", "-c"]
        args:
          - "while true; do echo \"$(date) - FAKETIME=${FAKETIME}\"; sleep 2; done"
