---
apiVersion: v1
kind: ConfigMap
metadata:
  name: insert-env
  namespace: ktailor
  labels:
    ktailor.io/template: "true"

data:
  template: |
    ---
    modifyContainers:
      insertOrOverwrite:
        env:
          - name: KTAILORTEST
            value: "Env set by central kTailor template."
